/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sof2041.view;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sof2041.Dao_service.Dao_serviec;
import sof2041.conect.DBconnect;
import sof2041.object.ChucVu;
import sof2041.object.PhongBan;

/**
 *
 * @author Admin
 */
public class infophongban extends javax.swing.JFrame {

    Connection con;
    Dao_serviec _Dao = new Dao_serviec();
    DefaultComboBoxModel<Object> cbomodel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Object> cbomodel2 = new DefaultComboBoxModel<>();
    String head[] = {"Mã NV", "Tên NV", "Ngày sinh ", "Địa chỉ", "Giới tính", "Dân tộc", "SĐT", "Mapb", "Mã CV", "Lương"};
    DefaultTableModel modeltable = new DefaultTableModel(head, 0);

    /**
     * Creates new form infophongban
     */
    public infophongban() {
        initComponents();
        try {
            con = DBconnect.getconnect("QLthongtin");
        } catch (Exception e) {
            System.out.println("LỖI " + e);
        }
        setLocationRelativeTo(this);
        cbophongban.setModel((DefaultComboBoxModel) cbomodel);
        cbochucvu.setModel((DefaultComboBoxModel) cbomodel2);
        tableList.setModel(modeltable);
        fillcombo();
        filltable();
        fillcombo2();

    }

    void fillcombo() {
        for (PhongBan x : _Dao.getlstphongban()) {
            cbomodel.addElement(x.getTenpb());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableList = new javax.swing.JTable();
        cbophongban = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblmapb = new javax.swing.JLabel();
        cbochucvu = new javax.swing.JComboBox<>();
        lblchucvu = new javax.swing.JLabel();
        lbltongso = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableList);

        cbophongban.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbophongban.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbophongbanItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Thông tin phòng ban");

        cbochucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbochucvu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbochucvuItemStateChanged(evt);
            }
        });

        btnexit.setText("Thoát");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbochucvu, 0, 225, Short.MAX_VALUE)
                            .addComponent(cbophongban, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblmapb, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnexit)
                                .addGap(42, 42, 42))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(lbltongso, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbochucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbophongban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmapb, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lbltongso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnexit)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbochucvuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbochucvuItemStateChanged
        // TODO add your handling code here:
        int i = cbochucvu.getSelectedIndex();
        ChucVu cv = _Dao.getlstchucvu().get(i);
        if (i != -1) {
            lblchucvu.setText(cv.getMacv());
            filltable2();
        }
    }//GEN-LAST:event_cbochucvuItemStateChanged

    private void cbophongbanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbophongbanItemStateChanged
        // TODO add your handling code here:
        int i = cbophongban.getSelectedIndex();
        PhongBan pb = _Dao.getlstphongban().get(i);
        if (i != -1) {
            lblmapb.setText(pb.getMapb());
            filltable();
        }
    }//GEN-LAST:event_cbophongbanItemStateChanged

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(infophongban.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infophongban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infophongban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infophongban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infophongban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infophongban().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JComboBox<String> cbochucvu;
    private javax.swing.JComboBox<String> cbophongban;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblchucvu;
    private javax.swing.JLabel lblmapb;
    private javax.swing.JLabel lbltongso;
    private javax.swing.JTable tableList;
    // End of variables declaration//GEN-END:variables

    private void filltable() {
        modeltable.setRowCount(0);
        String sql = "SELECT * FROM dbo.nhanvien WHERE mapb = ? ";
        int i = 1;
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, lblmapb.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                i++;
                modeltable.addRow(new Object[]{rs.getString(1), rs.getString(2),
                    rs.getString(3), rs.getString(4), rs.getString(4), rs.getInt(5),
                    rs.getString(6), rs.getString(7), rs.getString(9), rs.getFloat(10),});
                lbltongso.setText("Tổng số : " + (i - 1));
            }
        } catch (Exception e) {
        }
//        for (PhongBan x : _Dao.getlstphongban()) {
//            modeltable.addRow(new Object[]{x.getMapb(),x.getTenpb(),x.getDiachipb(),x.getSdtpb()});
//        }
    }

    private void fillcombo2() {
        for (ChucVu x : _Dao.getlstchucvu()) {
            cbomodel2.addElement(x.getTencv());
        }
    }

    private void filltable2() {
        modeltable.setRowCount(0);
        int i = 1;
        String sql = "SELECT * FROM dbo.nhanvien WHERE machucvu = ?";
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, lblchucvu.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                i++;
                modeltable.addRow(new Object[]{rs.getString(1), rs.getString(2),
                    rs.getString(3), rs.getString(4), rs.getString(4), rs.getInt(5),
                    rs.getString(6), rs.getString(7), rs.getString(8), rs.getFloat(10),});
                lbltongso.setText("Tổng số : " + (i - 1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
