/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sof2041.view;

import java.awt.Choice;
import java.sql.Connection;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sof2041.Dao_service.Dao_serviec;
import sof2041.conect.DBconnect;
import sof2041.object.ChucVu;
import sof2041.object.NhanVien;
import sof2041.object.PhongBan;
import java.sql.*;
import sof2041.object.user;

/**
 *
 * @author Admin
 */
public class viewnhanvien extends javax.swing.JFrame {

    login li = new login();
    Connection con;
    Dao_serviec _Dao = new Dao_serviec();
    String head[] = {"STT", "Mã NV", "Họ tên", "Ngày Sinh", "Địa chỉ", "Dân Tộc", "Chức vụ", "Giới tính", "Số Điện thoại", "Mã PB", "Lương"};
    DefaultTableModel model = new DefaultTableModel(head, 0);
    DefaultComboBoxModel<Object> combochucvu = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Object> combophongban = new DefaultComboBoxModel<>();
    String PB, CV;

    /**
     * Creates new form viewnhanvien
     */
    public viewnhanvien() {
        initComponents();
        try {
            con = DBconnect.getconnect("QLthongtin");
        } catch (Exception e) {
            System.out.println("LỖI " + e);
        }
        TableList.setModel(model);
        cboPhongban.setModel((DefaultComboBoxModel) combophongban);
        cbochucvu.setModel((DefaultComboBoxModel) combochucvu);
        setLocationRelativeTo(this);
        fillcombo();
        filltable();
    }

    private void filltable() {
        model.setRowCount(0);
        int i = 1;
        for (NhanVien x : _Dao.getlstnhanvien()) {

            model.addRow(new Object[]{i++, x.getManv(), x.getHoten(), x.getNgaysinh(),
                x.getDiachi(), x.getDantoc(), chucvu(x.getMachucvu()), gioitinh(x.getGioitinh()), x.getSdt().trim(),
                phongban(x.getMapb()), x.getLuong()});
//            System.out.println("x" + x);
            lbltongso.setText("Tổng số  : " + (i - 1));
        }
    }

    public String chucvu(String cv) {
        String a;
        for (ChucVu x : _Dao.getlstchucvu()) {
            if (x.getMacv().equals(cv)) {
                return a = x.getTencv();
            }
        }
        return null;
    }

    public String phongban(String pb) {
        String a;
        for (PhongBan x : _Dao.getlstphongban()) {
            if (x.getMapb().equals(pb)) {
                return a = x.getTenpb();
            }
        }
        return null;
    }

    public String gioitinh(int i) {
        String gt;
        if (i == 1) {
            return gt = "nam";
        }
        return gt = "nữ";
    }

    private void fillcombo() {

        for (ChucVu x : _Dao.getlstchucvu()) {
            combochucvu.addElement(x.getTencv());
//            System.out.println("x" + x.toString().trim());
        }
        for (PhongBan x : _Dao.getlstphongban()) {
            combophongban.addElement(x.getTenpb());
//            System.out.println("x" + x.toString().trim());
        }
    }

    public boolean deletenhanvien(String manv) {
        String sql = "DELETE dbo.nhanvien WHERE manv = ?";
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, manv);
            int ii = ps.executeUpdate();
            if (ii > 0) {
                return true;
            }
        } catch (Exception e) {
            System.out.println("Lỗi " + e);
        }
        return false;
    }

    public boolean deletetaikhoan(String manv) {
        String sql1 = "	delete taikhan where manv = ?";
        try {
            PreparedStatement ps = con.prepareStatement(sql1);
            ps.setString(1, manv);
            int resulset = ps.executeUpdate();
            if (resulset > 0) {
                JOptionPane.showMessageDialog(this, "xóa thành công nhân viên ", "thông báo ", JOptionPane.PLAIN_MESSAGE);
            }
            return true;
        } catch (Exception e) {
            System.out.println("Lỗi xóa user" + e);

        }
        return false;
    }

    public boolean checkrong(String string) {
        if (string.isBlank()) {
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableList = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JTextField();
        txtfullname = new javax.swing.JTextField();
        txtsalary = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdiachi = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtdantoc = new javax.swing.JTextField();
        rdbNam = new javax.swing.JRadioButton();
        rdbNu = new javax.swing.JRadioButton();
        txtsdt = new javax.swing.JTextField();
        cboPhongban = new javax.swing.JComboBox<>();
        cbochucvu = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnnew = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        lbltongso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableList);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Mã NV");

        jLabel3.setText("Họ Tên");

        jLabel4.setText("Lương");

        jLabel8.setText("Quê quán");

        txtdiachi.setColumns(20);
        txtdiachi.setRows(5);
        jScrollPane1.setViewportView(txtdiachi);

        jLabel10.setText("Giới tính");

        jLabel11.setText("Dân tộc");

        jLabel12.setText("SĐT");

        jLabel13.setText("Mã Phòng Ban");

        jLabel14.setText("Chức Vụ");

        buttonGroup1.add(rdbNam);
        rdbNam.setText("Nam");

        buttonGroup1.add(rdbNu);
        rdbNu.setText("Nữ");
        rdbNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNuActionPerformed(evt);
            }
        });

        cboPhongban.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPhongban.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPhongbanItemStateChanged(evt);
            }
        });

        cbochucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbochucvu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbochucvuItemStateChanged(evt);
            }
        });

        jLabel9.setText("Ngày sinh ( theo mẫu 01/01/2001)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsdt)
                                    .addComponent(txtdantoc)
                                    .addComponent(txtfullname, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtmanv, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 324, Short.MAX_VALUE)
                                        .addComponent(rdbNam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdbNu))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtsalary))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(cbochucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboPhongban, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtfullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(rdbNam)
                            .addComponent(rdbNu))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtdantoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cboPhongban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cbochucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(53, 53, 53))))
        );

        btnnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        btnnew.setText("Làm mới");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });
        jPanel2.add(btnnew);

        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnadd.setText("Thêm");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel2.add(btnadd);

        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Upload.png"))); // NOI18N
        btnupdate.setText("Cập nhập");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnupdate);

        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btndelete.setText("xóa");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btndelete);

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
        btnexit.setText("Thoát");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel2.add(btnexit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1125, Short.MAX_VALUE)
                .addComponent(lbltongso, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addComponent(lbltongso, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableListMouseClicked
        // TODO add your handling code here:
        int i = TableList.getSelectedRow();
        if (i >= 0) {
            txtmanv.setText((String) TableList.getValueAt(i, 1));
            txtfullname.setText((String) TableList.getValueAt(i, 2));
            txtngaysinh.setText((String) TableList.getValueAt(i, 3));
            txtdiachi.setText((String) TableList.getValueAt(i, 4));
            txtdantoc.setText((String) TableList.getValueAt(i, 5));
            if (TableList.getValueAt(i, 7) == "nam") {
                rdbNam.setSelected(true);
            } else {
                rdbNu.setSelected(true);
            }
//            if (TableList.getValueAt(i, 7) == "0") {
//                rdbNu.setSelected(true);
//            } else {
//                rdbNam.setSelected(true);
//            }
            for (PhongBan x : _Dao.getlstphongban()) {
                if (TableList.getValueAt(i, 9).equals(x.getMapb().toString().trim())) {
                    cboPhongban.setSelectedItem(x.getTenpb());
                }
            }
            for (ChucVu x : _Dao.getlstchucvu()) {
                if (TableList.getValueAt(i, 6).equals(x.getMacv().toString().trim())) {
                    cbochucvu.setSelectedItem(x.getTencv());
                }
            }
            txtsdt.setText((String) TableList.getValueAt(i, 8));
            txtsalary.setText(TableList.getValueAt(i, 10) + "");
        }

    }//GEN-LAST:event_TableListMouseClicked

    private void rdbNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbNuActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
        System.out.println("mã nv " + li.manv);
        ;
        txtfullname.setText("");
        txtmanv.setText("");
        txtngaysinh.setText("");
        txtsalary.setText("");

        txtngaysinh.setText("");
        txtdiachi.setText("");
        txtdantoc.setText("");
        txtsdt.setText("");
    }//GEN-LAST:event_btnnewActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        StringBuilder sb = new StringBuilder();
//        String sql = "update nhanvien set hoten = ?,gioitinh = ? ,dantoc = ? ,sdt = ? , mapb = ? ,machucvu = ?,luong = ? , ngaysinh = ? ,diachi = ? where manv = ?";
        if (checkrong(txtmanv.getText())) {
            sb.append("Mã nhân viên không được để trống !\n");
        }
        if (checkrong(txtfullname.getText())) {
            sb.append("Họ tên  nhân viên không được để trống !\n");
        }
        if (checkrong(txtdantoc.getText())) {
            sb.append("dân tộc  nhân viên không được để trống !\n");
        }
        if (checkrong(txtsdt.getText())) {
            sb.append("Số điện thoại  nhân viên không được để trống !\n");
        }
        if (checkrong(txtsalary.getText())) {
            sb.append("Lương nhân viên không được để trống !\n");
        }
        if (checkrong(txtngaysinh.getText())) {
            sb.append("Ngày sinh  nhân viên không được để trống !\n");
        }
        if (checkrong(txtdiachi.getText())) {
            sb.append("địa chỉ  nhân viên không được để trống !\n");
        }
        if (checknumber(txtsalary.getText())) {
            sb.append("Lương Phải nhập bằng số ");
        }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb, "thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                for (NhanVien x : _Dao.getlstnhanvien()) {
//                System.out.println(x);
                    if (txtmanv.getText().equals(x.getManv().toString().trim())) {
                        JOptionPane.showMessageDialog(this, "Mã Nhân viên trùng", "Thông báo", JOptionPane.WARNING_MESSAGE);
                        break;
                    }
                }
                String sql = "INSERT INTO dbo.nhanvien(manv, hoten, ngaysinh, diachi, gioitinh, dantoc, sdt, mapb, machucvu, luong)\n"
                        + "VALUES(?,?,?,?,?,?,?,?,?,?)";
                try {
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, txtmanv.getText());
                    ps.setString(2, txtfullname.getText());
                    ps.setString(3, txtngaysinh.getText());
                    ps.setString(4, txtdiachi.getText());
                    ps.setInt(5, rdbNam.isSelected() ? 1 : 0);
                    ps.setString(6, txtdantoc.getText());
                    ps.setString(7, txtsdt.getText());
                    ps.setString(8, PB);
                    ps.setString(9, CV);
                    ps.setString(10, txtsalary.getText());
                    int i = ps.executeUpdate();
                    if (i > 0) {
                        JOptionPane.showMessageDialog(this, "thêm thành công !", "thông báo ", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "không thành công ");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
//        if (checkrong(txtdantoc.getText()) || checkrong(txtdiachi.getText()) || checkrong(txtfullname.getText())
//                || checkrong(txtmanv.getText()) || checkrong(txtsalary.getText())
//                || checkrong(txtsdt.getText()) || checknumber(txtsalary.getText())) {
//            
//        } else {
//            JOptionPane.showMessageDialog(this, "không được để trống ", "thông báo", JOptionPane.WARNING_MESSAGE);
//        }

        filltable();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        String sql = "DELETE dbo.nhanvien WHERE manv = ?";
        int size = _Dao.getlistuser().size();
        StringBuilder sb = new StringBuilder();
        int i = JOptionPane.showConfirmDialog(this, "bạn có muốn xóa không ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            int a = TableList.getSelectedRow();
            for (user x : _Dao.getlistuser()) {
                if (TableList.getValueAt(a, 1).equals(x.getManv())) {
                    int choice = JOptionPane.showConfirmDialog(this, "Mã Nhân viên đã có tài khoản " + x.getUser().toString() + "\n bạn có muốn xóa tài khoản " + x.getUser().toString() + " không ?\n",
                            "thông bao", JOptionPane.WARNING_MESSAGE);
                    if (choice == JOptionPane.YES_OPTION) {
                        if (deletetaikhoan(TableList.getValueAt(a, 1).toString())) {
                            try {
                                PreparedStatement ps = con.prepareStatement(sql);
                                ps.setString(1, TableList.getValueAt(a, 1).toString());
                                int ii = ps.executeUpdate();
                                if (ii > 0) {
                                    JOptionPane.showMessageDialog(this, "xóa thành công !", "thông báo", JOptionPane.INFORMATION_MESSAGE);
                                    break;
                                } else {
                                    JOptionPane.showMessageDialog(this, "xóa thất bại", "thông báo", JOptionPane.INFORMATION_MESSAGE);

                                }
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                    }
                } else {
                    int c = 0;
                    System.out.println(c++);
                    size--;
                    if (size == 0) {
                        if (deletenhanvien(TableList.getValueAt(a, 1).toString())) {
                            JOptionPane.showMessageDialog(this, "Xóa Thành công nhân viên ", "Thông báo ", JOptionPane.WARNING_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(this, "Xóa KHông Thành công nhân viên ", "Thông báo ", JOptionPane.WARNING_MESSAGE);
                        }
                    }

                }
            }

        } else {

        }

        filltable();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
//        new mainfrom().setVisible(true);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        String sql = "update nhanvien set hoten = ?,gioitinh = ? ,dantoc = ? ,sdt = ? , mapb = ? ,machucvu = ?,luong = ? , ngaysinh = ? ,diachi = ? where manv = ?";
        if (checkrong(txtmanv.getText())) {
            sb.append("Mã nhân viên không được để trống !\n");
        }
        if (checkrong(txtfullname.getText())) {
            sb.append("Họ tên  nhân viên không được để trống !\n");
        }
        if (checkrong(txtdantoc.getText())) {
            sb.append("dân tộc  nhân viên không được để trống !\n");
        }
        if (checkrong(txtsdt.getText())) {
            sb.append("Số điện thoại  nhân viên không được để trống !\n");
        }
        if (checkrong(txtsalary.getText())) {
            sb.append("Lương nhân viên không được để trống !\n");
        }
        if (checkrong(txtngaysinh.getText())) {
            sb.append("Ngày sinh  nhân viên không được để trống !\n");
        }
        if (checkrong(txtdiachi.getText())) {
            sb.append("địa chỉ  nhân viên không được để trống !\n");
        }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb, "thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, txtfullname.getText());
                ps.setInt(2, rdbNam.isSelected() ? 1 : 0);
                ps.setString(3, txtdantoc.getText());
                ps.setString(4, txtsdt.getText());
                ps.setString(5, PB);
                ps.setString(6, CV);
                ps.setString(7, txtsalary.getText());
                ps.setString(8, txtngaysinh.getText());
                ps.setString(9, txtdiachi.getText());
                ps.setString(10, txtmanv.getText());
                int i = ps.executeUpdate();
                if (i > 0) {
                    JOptionPane.showMessageDialog(this, "Cập nhập thành công !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Thất bại", "thông báo", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
                System.out.println("Lỗi " + e);
            }
        }
        filltable();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void cboPhongbanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPhongbanItemStateChanged
        // TODO add your handling code here:
        int index = cboPhongban.getSelectedIndex();
        if (index != -1) {
            PhongBan pb = _Dao.getlstphongban().get(index);

            PB = pb.getMapb();
        }
    }//GEN-LAST:event_cboPhongbanItemStateChanged

    private void cbochucvuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbochucvuItemStateChanged
        // TODO add your handling code here:
//        System.out.println(evt);
        int index = cbochucvu.getSelectedIndex();
        if (index != -1) {
            System.out.println(index);
//                System.out.println("test: " +_dao.getlstchucvu().size());
            ChucVu cv = _Dao.getlstchucvu().get(index);

            CV = cv.getMacv();
//                System.out.println("in " + index);
//                System.out.println("cv " + cv.getMacv());
//                System.out.println("cv " + cbochucvu.getSelectedItem());
        }
    }//GEN-LAST:event_cbochucvuItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewnhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewnhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewnhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewnhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewnhanvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableList;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboPhongban;
    private javax.swing.JComboBox<String> cbochucvu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbltongso;
    private javax.swing.JRadioButton rdbNam;
    private javax.swing.JRadioButton rdbNu;
    private javax.swing.JTextField txtdantoc;
    private javax.swing.JTextArea txtdiachi;
    private javax.swing.JTextField txtfullname;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables

    private boolean checknumber(String text) {
        try {
            Float price = Float.parseFloat(text);
            return false;
        } catch (Exception e) {
            return true;
        }

    }
}
